services:
  contactsApp:
    build: 
      dockerfile: ./Dockerfile
      context: .
    command: flask run --host=0.0.0.0 --port=5125
    ports:
      - "5125:5125"
    env_file:
      - .env
    volumes:
      - .:/usr/app/contactsApp
      - /usr/app/contactsApp/instance