# version: "3.9"
services:
  python_backend:
    build: 
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    volumes:
      - .:${WORKDIR_FRONTEND} # volume to track app changes
      - ${DB_DIR} # volume to keep current database
    environment:
      # FLASK_EVN: development
      FLASK_EVN: production
      PORT: ${BACKEND_PORT}

  webapp_frontend:
    build: 
      context: ./webapp_frontend
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    env_file:
      - .env
    volumes:
      - .:${WORKDIR_FRONTEND} # volume to track app changes
    depends_on:
      - python_backend
    environment:
      # NODE_ENV: development
      NODE_ENV: production
      PORT: ${WEBAPP_PORT}