services:
  contacts_app:
    build: 
      dockerfile: ./Dockerfile
      context: .
    # command: flask run --host=0.0.0.0 --port=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/app/contacts_app # volume to track app changes
      - /usr/app/contacts_app/instance # volume to keep current database